### ISSUE TITLE
cannot connect to container based on latest dockerhub build of reporter 

### ISSUE THREAD

**Issue by mxndrwgrdnr** [opentraffic/reporter#90]
Opening an issue per our conversation today @kevinkreiser. 

All of my HTTP requests to a running instance of the newest Reporter image hung, not failing or timing out but never completing.

Similarly, Kevin was unable to `docker exec -it` into a Reporter instance based on the same latest image. 

Reverting back to older versions of the container fix the problem, so something must be going on with the latest build, aka `opentraffic/reporter:4c206e126c040fa98039611d91ccccd0ee618e09` or `opentraffic/reporter:latest`. Images starting at `opentraffic/reporter: c813127d3d41bf5a11b5a2f8fc38653f8454f60a` and earlier all seem to work fine.

**Comment by kevinkreiser** [comment]
turns out i was not able to reproduce this. i thought i was but really i was messing up the command.

so even with the latest i can confirm everything is working. heres how to do it with just some commands:

```bash
docker network create --driver bridge opentraffic
docker run --net opentraffic -p 8002:8002 --name reporter-py -v /data/valhalla:/data/valhalla opentraffic/reporter:latest
```

here's what a valid docker compose file looks like so you can just do `docker-compose up`:

```yml
version: "2"
services:

  reporter:
    image: opentraffic/reporter:latest
    network_mode: "bridge"
    ports:
      - "8003:8003"
    volumes:
      - ${VALHALLA_DOCKER_DATAPATH}:/data/valhalla
    environment:
      - MATCHER_LISTEN_PORT=8003
    container_name: reporter
```

notice the `newtwork_mode` set to `bridge` instead of `network` set to a name. having network set to a name doesnt work and always gives an error of `ERROR: Service "reporter" uses an undefined network "opentraffic"`
